# Numpy Tutoria  

## (NoteBook By Trushna Raut)

Numpy is a powerful and fundamental package for computations.
Numpy has the computational power of programming languages like C and Fortran. 
It is simple to learn and apply. It takes less space and less computation time.

To Install Numpy:
    pip install numpy

In [1]:
import  numpy as np  # It is way of importing numpy where as np is used as acronym

In [2]:
a1=np.array([1,2,3])  #single 1D array

In [3]:
a1  # you can simply see/print elements like this

array([1, 2, 3])

### Functions

In [4]:
type(a1)   #type of the array

numpy.ndarray

In [5]:
a1.ndim   #dimension of array

1

In [6]:
a1.shape  #shape of array 

(3,)

Note: 
There is difference between dimensions and shape. Dimension is measure in 1D,2D...ND
Where as shape of array is the number of elements in each dimension.

In [7]:
a1.dtype  #datatype of an array

dtype('int32')

In [8]:
a1.itemsize  #size of each item in array

4

In [9]:
a1.nbytes #number of bytes occupied by array. In this case, there are 3 elements each of size 4 = 4*3 = 12

12

In [10]:
a2=np.array([[1,2,3],[6,7,8]])  #single 2D arraay

In [11]:
a2

array([[1, 2, 3],
       [6, 7, 8]])

In [13]:
a2.shape  #which means it contains 2 rows and each row consits of 3 elements

(2, 3)

# Let's see how Numpy is fast than regular computation 

### Normal Computation VS Numpy Computation

In [7]:
import time ,sys

In [10]:
s=range(1000)
print(sys.getsizeof(s)*len(s))
d=np.arange(1000)
print(d.size*d.itemsize)

48000
4000


In [16]:
SIZE =1000000
l1=range(SIZE)
l2=range(SIZE)

m1=np.arange(SIZE)
m2=np.arange(SIZE)

start=time.time()
result=[(x,y) for x,y in zip(l1,l2)]
result
print((time.time()-start)*1000)

370.7730770111084


In [17]:
result1=m1*m2
result1
print((time.time()-start)*1000)

2689.7284984588623


##### reshape operation

In [3]:
a4=np.array([[1,2,3,4],[5,6,7,8]])

In [4]:
a4

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a4=a4.reshape(4,2) #reshaping into 4 rows 2 columns

In [6]:
a4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

##### slicing operation

In [9]:
print(a4[0,1])


2


In [14]:
a5=np.linspace(1,3,5)

In [13]:
a5

array([1. , 1.5, 2. , 2.5, 3. ])

In [25]:
c=np.array([[1,4,5,7,8,9,90,],[4,2,44,7,9,23,55]])

In [26]:
c[0,1:6:2]  

array([4, 7, 9])

In [28]:
#update element in array
c[1,5]=2222

In [29]:
c

array([[   1,    4,    5,    7,    8,    9,   90],
       [   4,    2,   44,    7,    9, 2222,   55]])

In [30]:
#modify column
c[:,2]=1000
c

array([[   1,    4, 1000,    7,    8,    9,   90],
       [   4,    2, 1000,    7,    9, 2222,   55]])

In [32]:
d=np.array([[[1,2],[3,4]],[[6,7],[8,9]]])

In [33]:
d

array([[[1, 2],
        [3, 4]],

       [[6, 7],
        [8, 9]]])

In [34]:
d[0,1,1]

4

In [35]:
d[:,1,:]

array([[3, 4],
       [8, 9]])

In [36]:
d[:,1,:]=[[9,9],[8,8]]

In [37]:
d

array([[[1, 2],
        [9, 9]],

       [[6, 7],
        [8, 8]]])

In [40]:
e=np.zeros((5,5))
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
f=np.zeros(5)
f

array([0., 0., 0., 0., 0.])

In [43]:
g=np.ones(10)
g

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
h=np.full((2,2),45)
h

array([[45, 45],
       [45, 45]])

In [59]:
i=np.random.rand(4,2)#rows and columns
i

array([[0.45179721, 0.14302372],
       [0.53340136, 0.37010261],
       [0.34328517, 0.09905958],
       [0.9446085 , 0.05737149]])

In [62]:
j=np.random.randint(78,size=(3,3))#78 is range of value of elements
j

array([[44, 73, 63],
       [20, 27,  0],
       [ 7, 69, 33]])

In [63]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [67]:
np.repeat(j,3,axis=1)

array([[44, 44, 44, 73, 73, 73, 63, 63, 63],
       [20, 20, 20, 27, 27, 27,  0,  0,  0],
       [ 7,  7,  7, 69, 69, 69, 33, 33, 33]])

In [72]:
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [73]:
output[1:4,1:4]=z


In [74]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
 #copy array elements
l=c.copy()

In [79]:
l

array([[   1,    4, 1000,    7,    8,    9,   90],
       [   4,    2, 1000,    7,    9, 2222,   55]])

In [77]:
print(l)

<built-in method copy of numpy.ndarray object at 0x000002571918CEE0>


In [80]:
l+2 #increment every element by 2

array([[   3,    6, 1002,    9,   10,   11,   92],
       [   6,    4, 1002,    9,   11, 2224,   57]])

In [82]:
l**2 #increment every element by power of 2

array([[      1,      16, 1000000,      49,      64,      81,    8100],
       [     16,       4, 1000000,      49,      81, 4937284,    3025]],
      dtype=int32)

In [83]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

Note : All the tutorials given above are learned from Edureka.